### PR TITLE
added support for ngrok2

### PR DESCRIPTION
**Pull request by Perf**
Hi please review changes!
The only one thing that should be done is in `lib/vagrant-foodshow/util/ngrok.rb` file at line 92: `# TODO target url`

### CODE REVIEW

**Comment by evtuhovich** [comment]
@sample Юра меня в скайпе попросил, я ему доверяю, мы с Титовым и Юрой вместе в Коннект.ЮА работали :-)

**Comment by Perf** [comment]
Спасибо!

**Comment by sample** [comment]
One problem with this PR, ngrok1 support have been broken. @Perf can you fix this?

**Comment by Perf** [comment]
Yes, I can )
The problem is - I don't know when. Probably I'll have some time next week.

**Comment by osminog** [comment]
@evtuhovich great Russian proverb says —  trust but check though ;)

**Pull request merged**
